# Basic Information
title: Yuchen Tu
position: Undergraduate Student
affiliation: Central China Normal University
affiliation_link: https://www.ccnu.edu.cn/
email: troytu90@gmail.com

# Search Engine Optimization (SEO)
keywords: Yuchen Tu, medical AI, trustworthy machine learning, large language models, healthcare AI
description: Personal academic homepage of Yuchen Tu.
canonical: https://troychen0513.github.io/

# Links
google_scholar:
cv_link:
github_link: https://github.com/Troychen0513
linkedin:
twitter:

# Images
avatar: ./assets/img/Troychen0513.jpg
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnote
enable_footnote: true

# Auto Dark Mode
auto_dark_mode: false

# Font
font: "Serif"

# Google Analytics ID
google_analytics:

# Use this project as a remote theme for GitHub Pages
remote_theme: yaoyao-liu/minimal-light

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
